#!/bin/sh

VERSION=666.development

if test -f version
then
	HERO_VERSION=$(cat version | awk -F'-' '{print $1}')
	HERO_RELEASE=$(cat version | awk -F'-' '{print $2}')
else
	DATE=$(date +%Y%m%d)
	GIT_COMMIT=$(git log --pretty=format:'%h' -n 1)
	HERO_VERSION=$VERSION
	# For custom package builds, replace "0" with "counter.your_name",
	# where counter starts at 1 and increments for successive versions.
	# This ensures that the package manager will select your custom
	# package over the standard release.
	HERO_BUILD=0
	HERO_RELEASE=$HERO_BUILD.$DATE.$GIT_COMMIT
fi

echo "$HERO_VERSION-$HERO_RELEASE"
mkdir -p build
echo "$HERO_VERSION" > build/HERO-VERSION-FILE
echo "$HERO_RELEASE" > build/HERO-RELEASE-FILE
